services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  postgres:
    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres:/var/lib/postgresql/data
    image: postgres:13.3
    environment:
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_PASS: root
      RABBITMQ_DEFAULT_USER: root
    ports:
      - 5672:5672